from autolog.agent.backend import LLMBackend
from autolog.agent.prompts import ENTRY_SYSTEM_PROMPT, QUERY_SYSTEM_PROMPT


class AgentCore:
    def __init__(self, backend: LLMBackend) -> None:
        self.backend = backend

    def create_entry(
        self,
        raw_note: str,
        timestamp: str,
        image_path: str | None = None,
    ) -> str:
        """Convert a rough note into a formatted Markdown log entry.

        Args:
            raw_note:   The user's unstructured note text.
            timestamp:  ISO 8601 timestamp string (generated by the caller).
            image_path: Optional path to an image file to include in the entry.

        Returns:
            A formatted Markdown entry string. Does NOT write to disk.
        """
        system_prompt = ENTRY_SYSTEM_PROMPT.replace("{timestamp}", timestamp)

        user_content = f"Timestamp: {timestamp}\n\nNote:\n{raw_note}"
        if image_path is not None:
            user_content += f"\n\nAn image has been attached: {image_path}"

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_content},
        ]

        return self.backend.generate(messages, image_path=image_path)

    def answer_query(self, question: str, context_entries: list[str]) -> str:
        """Answer a question using retrieved log entries as context.

        Args:
            question:        The user's natural-language question.
            context_entries: List of raw entry strings from VectorStore.search().

        Returns:
            LLM-generated answer string with timestamp citations.
        """
        context = "\n\n---\n\n".join(context_entries)
        system_prompt = QUERY_SYSTEM_PROMPT.replace("{context}", context)
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": question},
        ]
        return self.backend.generate(messages)
