services:
  autolog:
    build:
      context: .
      dockerfile: Dockerfile.mac
    container_name: autolog
    volumes:
      - .:/workspace
    working_dir: /workspace
    user: "${UID}:${GID}"
    stdin_open: true
    tty: true
