services:
  autolog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autolog
    volumes:
      - .:/workspace
    working_dir: /workspace
    user: "${UID}:${GID}"
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
